services:
  web:
    build: .
    container_name: app_ci_v3_web
    restart: always

    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT:-Production}

      ConnectionStrings__DefaultConnection: "Server=${DB_HOST};Port=${DB_PORT:-3306};Database=${DB_NAME};User Id=${DB_USER};Password=${DB_PASSWORD};"

      DataProtection__KeysPath: ${DATA_PROTECTION_KEYS_PATH:-/root/.aspnet/DataProtection-Keys}

    ports:
      - "${APP_HTTP_PORT:-5016}:5014"

    volumes:
      - app_ci_v3_keys:/root/.aspnet/DataProtection-Keys
      - app_ci_v3_logs:/app/Logs

volumes:
  app_ci_v3_keys:
  app_ci_v3_logs: